-- This migration was created to restore original schema
-- However, all tables and enums already exist from previous migrations:
-- - UserRole enum and users table: created in 20250928105145_init
-- - ambassador_profiles, social_links, following: created in 20251007053747_add_ambassador_profile
-- This migration is now empty to avoid duplicate creation errors
-- No SQL changes needed
